server:
  ssl:
    enabled: false

spring:
  cloud:
    openfeign:
      client:
        config:
          anilist:
            logger-level: basic
          default:
            logger-level: basic
  datasource:
    url: jdbc:postgresql://localhost:5432/deus-bot
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    ru.demetrious.deus.bot: debug
    org.hibernate.orm.jdbc.bind: info
    com.sedmelluq.discord.lavaplayer: info
    dev.lavalink.youtube: info
    net.dv8tion.jda: info
    org.springframework.web.socket: info
    org.springframework.messaging: info
    org.springframework.messaging.simp.annotation.support.SimpAnnotationMethodMessageHandler: info
    org.springframework.messaging.simp.user: info
    org.springframework.messaging.simp.broker: info

devs:
  ids: ${DEVS_DISCORD_IDS:}


cache:
  files-path: ./.cache-data
  configs:
    shikimori-franchises:
      expire-after-write: 36500d
    reverse1999-data:
      expire-after-write: 36500d
