spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: FULL
  datasource:
    url: jdbc:postgresql://localhost:5432/deus-bot
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    ru.demetrious.deus.bot: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    com.sedmelluq.discord.lavaplayer: DEBUG
    dev.lavalink.youtube: DEBUG

devs:
  ids: ${DEVS_DISCORD_IDS:}
