spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: basic
  datasource:
    url: jdbc:postgresql://localhost:5432/deus-bot
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    ru.demetrious.deus.bot: debug
    org.hibernate.orm.jdbc.bind: info
    com.sedmelluq.discord.lavaplayer: info
    dev.lavalink.youtube: info

devs:
  ids: ${DEVS_DISCORD_IDS:}
