name: Pre-release
on:
  workflow_dispatch:
    inputs:
      operation:
        required: true
        type: choice
        default: deploy
        description: What operation to start
        options:
          - deploy
          - stop
          - restart

env:
  IMAGE_NAME: deus-bot-test
  LOCAL_IMAGE_NAME: deus-bot

jobs:
  install:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    outputs:
      url: ${{ steps.getImageUrl.outputs.url }}

    if: contains(inputs.operation, 'deploy')

    steps:
      - uses: actions/checkout@v4

      - name: Pull new version
        run: git pull --rebase

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'graalvm'

      - name: Build a container image from Spring Boot app using maven
        run: mvn spring-boot:build-image

      - name: Set image url output variable
        id: getImageUrl
        run: echo "url=ghcr.io/${GITHUB_REPOSITORY%/*}/${{ env.IMAGE_NAME }}:test" >> $GITHUB_OUTPUT

      - name: Tag docker image
        run: docker tag ${{ env.LOCAL_IMAGE_NAME }}:$(mvn help:evaluate -Dexpression=revision -q -DforceStdout) ${{ steps.getImageUrl.outputs.url }}

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Publish to GitHub Container Registry
        run: docker push ${{ steps.getImageUrl.outputs.url }}

  stop:
    runs-on: ubuntu-latest

    env:
      # Build secrets
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    if: inputs.operation == 'deploy' || inputs.operation == 'restart' || inputs.operation == 'stop'

    steps:
      - name: Run multiple remote commands via SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            docker container rm -f ${{ env.IMAGE_NAME }} || true

  deploy:
    runs-on: ubuntu-latest

    needs:
      - install
      - stop

    environment: 'pre-production'

    env:
      # Build secrets
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      # Build vars
      CONTAINER_MEMORY_LIMIT: ${{ vars.CONTAINER_MEMORY_LIMIT }}
      GITHUB_ACTOR: ${{ github.actor }}

      # App secrets
      ANILIST_OAUTH2_ID: ${{ secrets.ANILIST_OAUTH2_ID }}
      ANILIST_OAUTH2_SECRET: ${{ secrets.ANILIST_OAUTH2_SECRET }}
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DISCORD_OAUTH2_ID: ${{ secrets.DISCORD_OAUTH2_ID }}
      DISCORD_OAUTH2_SECRET: ${{ secrets.DISCORD_OAUTH2_SECRET }}
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
      SHIKIMORI_OAUTH2_ID: ${{ secrets.SHIKIMORI_OAUTH2_ID }}
      SHIKIMORI_OAUTH2_SECRET: ${{ secrets.SHIKIMORI_OAUTH2_SECRET }}
      YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}
      # App vars
      ANILIST_GRAPHQL_URL: ${{ vars.ANILIST_GRAPHQL_URL }}
      ANILIST_URL: ${{ vars.ANILIST_URL }}
      APP_URL: ${{ vars.APP_URL }}
      ARTING_URL: ${{ vars.ARTING_URL }}
      DATABASE_MAX_POOL: ${{ vars.DATABASE_MAX_POOL }}
      DATABASE_URL: ${{ vars.DATABASE_URL }}
      DISCORD_URL: ${{ vars.DISCORD_URL }}
      FREE_STEAM_URL: ${{ vars.FREE_STEAM_URL }}
      SHIKIMORI_GRAPHQL_PATH: ${{ vars.SHIKIMORI_GRAPHQL_PATH }}
      SHIKIMORI_URL: ${{ vars.SHIKIMORI_URL }}
      DEUS_URL: ${{ vars.DEUS_URL }}

    if: |
      (inputs.operation == 'deploy' && needs.install.result == 'success' && needs.stop.result == 'success') ||
      (inputs.operation == 'restart' && needs.stop.result == 'success')

    steps:
      - name: Run multiple remote commands via SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            docker run -d -p 8080:8080 -m ${{ env.CONTAINER_MEMORY_LIMIT }} --pull always --restart always --name ${{ env.IMAGE_NAME }} \
              -e ANILIST_OAUTH2_ID=${{ env.ANILIST_OAUTH2_ID }} \
              -e ANILIST_OAUTH2_SECRET=${{ env.ANILIST_OAUTH2_SECRET }} \
              -e DATABASE_USERNAME=${{ env.DATABASE_USERNAME }} \
              -e DATABASE_PASSWORD=${{ env.DATABASE_PASSWORD }} \
              -e DISCORD_OAUTH2_ID=${{ env.DISCORD_OAUTH2_ID }} \
              -e DISCORD_OAUTH2_SECRET=${{ env.DISCORD_OAUTH2_SECRET }} \
              -e DISCORD_TOKEN=${{ env.DISCORD_TOKEN }} \
              -e KEY_STORE_PASSWORD=${{ env.KEY_STORE_PASSWORD }} \
              -e SHIKIMORI_OAUTH2_ID=${{ env.SHIKIMORI_OAUTH2_ID }} \
              -e SHIKIMORI_OAUTH2_SECRET=${{ env.SHIKIMORI_OAUTH2_SECRET }} \
              -e YOUTUBE_REFRESH_TOKEN=${{ env.YOUTUBE_REFRESH_TOKEN }} \
              \
              -e ANILIST_GRAPHQL_URL=${{ vars.ANILIST_GRAPHQL_URL }} \
              -e ANILIST_URL=${{ vars.ANILIST_URL }} \
              -e APP_URL=${{ vars.APP_URL }} \
              -e ARTING_URL=${{ vars.ARTING_URL }} \
              -e DATABASE_MAX_POOL=${{ vars.DATABASE_MAX_POOL }} \
              -e DATABASE_URL=${{ vars.DATABASE_URL }} \
              -e DISCORD_URL=${{ vars.DISCORD_URL }} \
              -e FREE_STEAM_URL=${{ vars.FREE_STEAM_URL }} \
              -e SHIKIMORI_GRAPHQL_PATH=${{ vars.SHIKIMORI_GRAPHQL_PATH }} \
              -e SHIKIMORI_URL=${{ vars.SHIKIMORI_URL }} \
              -e DEUS_URL=${{ vars.DEUS_URL }} \
            ghcr.io/${{ env.GITHUB_ACTOR }}/${{ env.IMAGE_NAME }}:test
